FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS base
WORKDIR /PF
EXPOSE 80


FROM mcr.microsoft.com/dotnet/core/sdk AS build
WORKDIR /project
COPY  ["/", "/project"]
# WORKDIR /project/Osn.Payment.Facade/Web/Osn.Payment.Facade.Web/
# RUN curl http://google.com

// add Path for project
RUN dotnet restore "*.csproj"
// add Path for project
RUN dotnet build "*.csproj" 


FROM build as publish
RUN dotnet publish "*.csproj" -c Debug -o /PF

FROM base as final
WORKDIR /PF
COPY --from=publish /PF .
ENTRYPOINT ["dotnet", ".dll"]
